---
- name: Remove old packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Setup repository
  yum:
    name:
      - yum-utils
    state: latest
    update_cache: yes

- name: Add updated Docker repo
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/centos_o.repo

- name: Enable Docker nightly ce
  shell: yum-config-manager --enable docker-ce-nightly

- name: Install docker engine
  yum:
    name:
     - docker-ce 
     - docker-ce-cli 
     - containerd.io
    state: latest
    update_cache: yes
